// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package dbgen

import (
	"context"
)

const getConfigForUpdate = `-- name: GetConfigForUpdate :one
SELECT id, data_value FROM web_config WHERE data_key = ? ORDER BY id LIMIT 1 FOR UPDATE
`

type GetConfigForUpdateRow struct {
	ID        int32
	DataValue string
}

func (q *Queries) GetConfigForUpdate(ctx context.Context, dataKey string) (GetConfigForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getConfigForUpdate, dataKey)
	var i GetConfigForUpdateRow
	err := row.Scan(&i.ID, &i.DataValue)
	return i, err
}

const insertConfig = `-- name: InsertConfig :exec
INSERT INTO web_config (data_key, data_value) VALUES (?, ?)
`

type InsertConfigParams struct {
	DataKey   string
	DataValue string
}

func (q *Queries) InsertConfig(ctx context.Context, arg InsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, insertConfig, arg.DataKey, arg.DataValue)
	return err
}

const listConfig = `-- name: ListConfig :many
SELECT id, data_key, data_value FROM web_config ORDER BY id
`

func (q *Queries) ListConfig(ctx context.Context) ([]WebConfig, error) {
	rows, err := q.db.QueryContext(ctx, listConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebConfig
	for rows.Next() {
		var i WebConfig
		if err := rows.Scan(&i.ID, &i.DataKey, &i.DataValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE web_config SET data_value = ? WHERE id = ?
`

type UpdateConfigParams struct {
	DataValue string
	ID        int32
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig, arg.DataValue, arg.ID)
	return err
}
