// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package dbgen

import (
	"context"
)

const createGroup = `-- name: CreateGroup :execlastid
INSERT INTO page_group (group_name, page_sort) VALUES (?, '[]')
`

func (q *Queries) CreateGroup(ctx context.Context, groupName string) (int64, error) {
	result, err := q.db.ExecContext(ctx, createGroup, groupName)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM page_group WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, group_name, page_sort FROM page_group WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (PageGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i PageGroup
	err := row.Scan(&i.ID, &i.GroupName, &i.PageSort)
	return i, err
}

const getGroupForUpdate = `-- name: GetGroupForUpdate :one
SELECT id, group_name, page_sort FROM page_group WHERE id = ? FOR UPDATE
`

func (q *Queries) GetGroupForUpdate(ctx context.Context, id int64) (PageGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroupForUpdate, id)
	var i PageGroup
	err := row.Scan(&i.ID, &i.GroupName, &i.PageSort)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, group_name, page_sort FROM page_group ORDER BY id
`

func (q *Queries) ListGroups(ctx context.Context) ([]PageGroup, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageGroup
	for rows.Next() {
		var i PageGroup
		if err := rows.Scan(&i.ID, &i.GroupName, &i.PageSort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameGroup = `-- name: RenameGroup :execrows
UPDATE page_group SET group_name = ? WHERE id = ?
`

type RenameGroupParams struct {
	GroupName string
	ID        int64
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameGroup, arg.GroupName, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGroupPageSort = `-- name: UpdateGroupPageSort :exec
UPDATE page_group SET page_sort = ? WHERE id = ?
`

type UpdateGroupPageSortParams struct {
	PageSort string
	ID       int64
}

func (q *Queries) UpdateGroupPageSort(ctx context.Context, arg UpdateGroupPageSortParams) error {
	_, err := q.db.ExecContext(ctx, updateGroupPageSort, arg.PageSort, arg.ID)
	return err
}
