// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package dbgen

import (
	"context"
)

const createCarousel = `-- name: CreateCarousel :execlastid
INSERT INTO carousel (image, url) VALUES (?, ?)
`

type CreateCarouselParams struct {
	Image string
	Url   string
}

func (q *Queries) CreateCarousel(ctx context.Context, arg CreateCarouselParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCarousel, arg.Image, arg.Url)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createMarquee = `-- name: CreateMarquee :execlastid
INSERT INTO marquee (text, color) VALUES (?, ?)
`

type CreateMarqueeParams struct {
	Text  string
	Color string
}

func (q *Queries) CreateMarquee(ctx context.Context, arg CreateMarqueeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMarquee, arg.Text, arg.Color)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteCarousel = `-- name: DeleteCarousel :execrows
DELETE FROM carousel WHERE id = ?
`

func (q *Queries) DeleteCarousel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCarousel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMarquee = `-- name: DeleteMarquee :execrows
DELETE FROM marquee WHERE id = ?
`

func (q *Queries) DeleteMarquee(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMarquee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findCarouselsUsingText = `-- name: FindCarouselsUsingText :many
SELECT id, image, url FROM carousel WHERE INSTR(image, ?) > 0 ORDER BY id
`

func (q *Queries) FindCarouselsUsingText(ctx context.Context, needle string) ([]Carousel, error) {
	rows, err := q.db.QueryContext(ctx, findCarouselsUsingText, needle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carousel
	for rows.Next() {
		var i Carousel
		if err := rows.Scan(&i.ID, &i.Image, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCarousel = `-- name: GetCarousel :one
SELECT id, image, url FROM carousel WHERE id = ?
`

func (q *Queries) GetCarousel(ctx context.Context, id int64) (Carousel, error) {
	row := q.db.QueryRowContext(ctx, getCarousel, id)
	var i Carousel
	err := row.Scan(&i.ID, &i.Image, &i.Url)
	return i, err
}

const getMarquee = `-- name: GetMarquee :one
SELECT id, text, color FROM marquee WHERE id = ?
`

func (q *Queries) GetMarquee(ctx context.Context, id int64) (Marquee, error) {
	row := q.db.QueryRowContext(ctx, getMarquee, id)
	var i Marquee
	err := row.Scan(&i.ID, &i.Text, &i.Color)
	return i, err
}

const listCarousels = `-- name: ListCarousels :many
SELECT id, image, url FROM carousel ORDER BY id
`

func (q *Queries) ListCarousels(ctx context.Context) ([]Carousel, error) {
	rows, err := q.db.QueryContext(ctx, listCarousels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carousel
	for rows.Next() {
		var i Carousel
		if err := rows.Scan(&i.ID, &i.Image, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarquees = `-- name: ListMarquees :many
SELECT id, text, color FROM marquee ORDER BY id
`

func (q *Queries) ListMarquees(ctx context.Context) ([]Marquee, error) {
	rows, err := q.db.QueryContext(ctx, listMarquees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Marquee
	for rows.Next() {
		var i Marquee
		if err := rows.Scan(&i.ID, &i.Text, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCarousel = `-- name: UpdateCarousel :execrows
UPDATE carousel SET image = ?, url = ? WHERE id = ?
`

type UpdateCarouselParams struct {
	Image string
	Url   string
	ID    int64
}

func (q *Queries) UpdateCarousel(ctx context.Context, arg UpdateCarouselParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCarousel, arg.Image, arg.Url, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMarquee = `-- name: UpdateMarquee :execrows
UPDATE marquee SET text = ?, color = ? WHERE id = ?
`

type UpdateMarqueeParams struct {
	Text  string
	Color string
	ID    int64
}

func (q *Queries) UpdateMarquee(ctx context.Context, arg UpdateMarqueeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarquee, arg.Text, arg.Color, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
