// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Carousel struct {
	// 流水號
	ID int64
	// 圖片網址
	Image string
	// 網址
	Url string
}

type Marquee struct {
	// 流水號
	ID int64
	// 文字內容
	Text string
	// 色碼
	Color string
}

type PageContent struct {
	// 流水號
	ID int64
	// 群組ID
	PageGroupID int64
	// 分頁名稱
	PageName string
	// 內頁資料(html)
	HtmlContext string
}

type PageGroup struct {
	// 流水號
	ID int64
	// 群組名稱
	GroupName string
	// 內頁順序
	PageSort string
}

type User struct {
	// 流水號
	ID int64
	// 帳號
	Account string
	// 密碼（bcrypt）
	Pwd string
	// 1.管理者
	Identity int32
	// 暱稱
	UserName string
}

type UserToken struct {
	// 使用者ID
	UserID int64
	// 登入 token（SHA-256）
	Token string
	// 過期時間
	ExpireTime time.Time
}

type WebConfig struct {
	// 流水號
	ID int32
	// Key
	DataKey string
	// 值
	DataValue string
}
