// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package dbgen

import (
	"context"
)

const countPagesInGroup = `-- name: CountPagesInGroup :one
SELECT COUNT(*) FROM page_content WHERE page_group_id = ?
`

func (q *Queries) CountPagesInGroup(ctx context.Context, pageGroupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPagesInGroup, pageGroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :execlastid
INSERT INTO page_content (page_group_id, page_name, html_context) VALUES (?, ?, ?)
`

type CreatePageParams struct {
	PageGroupID int64
	PageName    string
	HtmlContext string
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPage, arg.PageGroupID, arg.PageName, arg.HtmlContext)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM page_content WHERE id = ?
`

func (q *Queries) DeletePage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const findPagesUsingText = `-- name: FindPagesUsingText :many
SELECT id, page_name FROM page_content WHERE INSTR(html_context, ?) > 0 ORDER BY id
`

type FindPagesUsingTextRow struct {
	ID       int64
	PageName string
}

func (q *Queries) FindPagesUsingText(ctx context.Context, needle string) ([]FindPagesUsingTextRow, error) {
	rows, err := q.db.QueryContext(ctx, findPagesUsingText, needle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPagesUsingTextRow
	for rows.Next() {
		var i FindPagesUsingTextRow
		if err := rows.Scan(&i.ID, &i.PageName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPage = `-- name: GetPage :one
SELECT id, page_group_id, page_name, html_context FROM page_content WHERE id = ?
`

func (q *Queries) GetPage(ctx context.Context, id int64) (PageContent, error) {
	row := q.db.QueryRowContext(ctx, getPage, id)
	var i PageContent
	err := row.Scan(
		&i.ID,
		&i.PageGroupID,
		&i.PageName,
		&i.HtmlContext,
	)
	return i, err
}

const getPageForUpdate = `-- name: GetPageForUpdate :one
SELECT id, page_group_id, page_name, html_context FROM page_content WHERE id = ? FOR UPDATE
`

func (q *Queries) GetPageForUpdate(ctx context.Context, id int64) (PageContent, error) {
	row := q.db.QueryRowContext(ctx, getPageForUpdate, id)
	var i PageContent
	err := row.Scan(
		&i.ID,
		&i.PageGroupID,
		&i.PageName,
		&i.HtmlContext,
	)
	return i, err
}

const listPageIDsInGroup = `-- name: ListPageIDsInGroup :many
SELECT id FROM page_content WHERE page_group_id = ? ORDER BY id
`

func (q *Queries) ListPageIDsInGroup(ctx context.Context, pageGroupID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPageIDsInGroup, pageGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageSummaries = `-- name: ListPageSummaries :many
SELECT id, page_group_id, page_name FROM page_content ORDER BY id
`

type ListPageSummariesRow struct {
	ID          int64
	PageGroupID int64
	PageName    string
}

func (q *Queries) ListPageSummaries(ctx context.Context) ([]ListPageSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPageSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPageSummariesRow
	for rows.Next() {
		var i ListPageSummariesRow
		if err := rows.Scan(&i.ID, &i.PageGroupID, &i.PageName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :exec
UPDATE page_content SET page_group_id = ?, page_name = ?, html_context = ? WHERE id = ?
`

type UpdatePageParams struct {
	PageGroupID int64
	PageName    string
	HtmlContext string
	ID          int64
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage,
		arg.PageGroupID,
		arg.PageName,
		arg.HtmlContext,
		arg.ID,
	)
	return err
}
