// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :execlastid
INSERT INTO ` + "`" + `user` + "`" + ` (account, pwd, identity, user_name) VALUES (?, ?, 1, ?)
`

type CreateUserParams struct {
	Account  string
	Pwd      string
	UserName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUser, arg.Account, arg.Pwd, arg.UserName)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_token WHERE user_id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, userID)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE user_token SET expire_time = ? WHERE user_id = ?
`

type ExtendSessionParams struct {
	ExpireTime time.Time
	UserID     int64
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.ExecContext(ctx, extendSession, arg.ExpireTime, arg.UserID)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT user_id, token, expire_time FROM user_token WHERE token = ? LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (UserToken, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i UserToken
	err := row.Scan(&i.UserID, &i.Token, &i.ExpireTime)
	return i, err
}

const getUserByAccount = `-- name: GetUserByAccount :one
SELECT id, account, pwd, identity, user_name FROM ` + "`" + `user` + "`" + ` WHERE account = ? ORDER BY id LIMIT 1
`

func (q *Queries) GetUserByAccount(ctx context.Context, account string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAccount, account)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Pwd,
		&i.Identity,
		&i.UserName,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, account, pwd, identity, user_name FROM ` + "`" + `user` + "`" + ` WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Pwd,
		&i.Identity,
		&i.UserName,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE ` + "`" + `user` + "`" + ` SET pwd = ? WHERE account = ?
`

type UpdateUserPasswordParams struct {
	Pwd     string
	Account string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPassword, arg.Pwd, arg.Account)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSession = `-- name: UpsertSession :exec
REPLACE INTO user_token (user_id, token, expire_time) VALUES (?, ?, ?)
`

type UpsertSessionParams struct {
	UserID     int64
	Token      string
	ExpireTime time.Time
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession, arg.UserID, arg.Token, arg.ExpireTime)
	return err
}
